### PR TITLE
correct viewport decoding (false colors), minor typos

### PR DESCRIPTION
**Pull request by kralo**
top: old, wrong
bottom: better
illustration

### CODE REVIEW

**Comment by ankhazam** [comment]
Hi,
thanks for the update but prior to merging it you need to update the build.gradle file with proper version of the library in accordance to http://semver.org/. This is required to automatically propagate the changes into new artifacts available onlie

**Comment by kralo** [comment]
hmm, not sure what you want me to do here, since we're on 0.5.4.
`Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
` [semver#4](http://semver.org/#spec-item-4)
Do you want to go on 0.6.0 ?

**Comment by ankhazam** [comment]
Yes, going 0.6.0 is a better idea than not changing anything at all whilst breaking the API :)

**Comment by kralo** [comment]
done

**Pull request merged**
